### ISSUE TITLE
gum_thumb_relocator_can_relocate: assertion failed: (insn != NULL)

### ISSUE THREAD

**Issue by daniula** [frida/frida#134] opened 2016-04-05 11:18 UTC
From adb logcat:

```
04-05 13:14:51.693 14387 14532 F Frida   : frida-gum/gum/arch-arm/gumthumbrelocator.c:378:gum_thumb_relocator_can_relocate: assertion failed: (insn != NULL)
04-05 13:14:51.693 14387 14532 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 14532 (gum-js-loop)
04-05 13:14:51.795   196   196 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-05 13:14:51.795   196   196 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MMB29K/2419427:user/release-keys'
04-05 13:14:51.795   196   196 F DEBUG   : Revision: '0'
04-05 13:14:51.795   196   196 F DEBUG   : ABI: 'arm'
04-05 13:14:51.795   196   196 F DEBUG   : pid: 14387, tid: 14532, name: gum-js-loop  >>> com.twitter.android <<<
04-05 13:14:51.795   196   196 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-05 13:14:51.828   196   196 F DEBUG   : Abort message: 'frida-gum/gum/arch-arm/gumthumbrelocator.c:378:gum_thumb_relocator_can_relocate: assertion failed: (insn != NULL)'
04-05 13:14:51.828   196   196 F DEBUG   :     r0 00000000  r1 000038c4  r2 00000006  r3 926f4978
04-05 13:14:51.828   196   196 F DEBUG   :     r4 926f4980  r5 926f4930  r6 00000000  r7 0000010c
04-05 13:14:51.828   196   196 F DEBUG   :     r8 96614bb0  r9 0000017a  sl 9669add1  fp 926f42ac
04-05 13:14:51.828   196   196 F DEBUG   :     ip 00000006  sp 926f41c8  lr b6c7fb61  pc b6c81f50  cpsr 400f0010
04-05 13:14:51.829   196   196 F DEBUG   :
04-05 13:14:51.829   196   196 F DEBUG   : backtrace:
04-05 13:14:51.829   196   196 F DEBUG   :     #00 pc 00001f50  /system/lib/libc.so (offset 0x40000)
04-05 13:14:51.829   196   196 F DEBUG   :     #01 pc 00000b5d  /system/lib/libc.so (offset 0x3f000)
04-05 13:14:52.841   196   196 F DEBUG   :
04-05 13:14:52.841   196   196 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_04
04-05 13:14:52.841   196   196 E DEBUG   : AM write failed: Broken pipe
```

**Comment by oleavr** [comment] 2017-01-19 00:29
Fixed in latest Frida 9.x.

**Closed by oleavr** 2017-01-19 00:29 UTC

**Comment by jdrowell** [comment] 2018-04-05 15:32
To give more context, I'm hooking several functions just fine, but weirdly it seems that after a certain address (same segment), any hooks I add give a SIGABRT. The code I'm analyzing is malicious, so the signal may be caused by anti-hooking techniques which I haven't identified.
