### ISSUE TITLE
Failed to inject frida-agent into launchd(pid 1) on iOS 14.5 jailbroken with Checkra1n 0.12.3

### ISSUE THREAD

**Issue by EddaAkikusa** [frida/frida#1719] opened 2021-05-03 13:17 UTC
I'll get such error messages when connecting to `frida-server`
```
process with pid 1 either refused to load frida-agent, or terminated during injection
```

**Comment by as0ler** [comment] 2021-05-03 21:41
I can confirm the bug. It ocurrs when attaching or spawning a new process. 

Tested on Frida 14.2.17 with iPhone X and Checkra1n 0.12.3.

Logs:

```
 ᐅ frida -U -f com.apple.mobilesafari
     ____
    / _  |   Frida 14.2.17 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to spawn: process with pid 1 either refused to load frida-agent, or terminated during injection

frida -U -n Safari
     ____
    / _  |   Frida 14.2.17 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to attach: process with pid 1671 either refused to load frida-agent, or terminated during injection
```

**Comment by 0xItx** [comment] 2021-05-04 10:14
I can confirm this happens with 14.2.17 on 14.5 while trying to attach or spawn a process:
`Unable to create connection: Error sending credentials: Error sending message: Broken pipe`

**Comment by AnaCosteira** [comment] 2021-05-04 11:20
Same here. 
Problem seems to be valid for all frida on 14.2.X. 
iOS is running frida available in Cydia's https://build.frida.re/.

Also it's valid for PID, identifier or app name.

**Comment by r3ggi** [comment] 2021-05-07 14:37
Yeah, I have the same problem

**Comment by w0x12ef** [comment] 2021-05-18 05:25
same problem

**Comment by OS0day** [comment] 2021-06-30 08:43
excuse me？I hava the same problem.  While，can you give me  a Oplossing？SOS！！

**Comment by forensicmike** [comment] 2021-08-03 21:54
Still running into this on frida-tools v15.0.2, frida-server 15.0.8 and 15.0.13 (latest). I tested it on two different jb devices (iPhone SE iOS 14.6, iPhone 6s iOS 14.3). **Note**: Injection is working fine to many processes, but not `cfprefsd` or `backboardd` (Apple daemons). Attaching to *some* daemons does work , including launchd.

**Comment by oleavr** [comment] 2021-09-03 22:52
Thanks for reporting! This should now be fixed in Frida 15.1.0.

**Closed by oleavr** 2021-09-03 22:52 UTC

**Comment by AZsansan** [comment] 2021-10-04 09:37
My Frida version is 15.1.3, but I still got the problem "Failed to attach: process with pid 7651 either refused to load frida-agent, or terminated during injection"😢😢

**Comment by bartlomiejduda** [comment] 2022-01-04 23:05
I'm getting this error on Frida 15.1.14 on Android device.

Why this issue is closed when it isn't really fixed?

**Comment by oleavr** [comment] 2022-01-05 00:29
@bartlomiejduda This issue is about iOS. If you're running into issues on Android, please open a separate issue describing how it may be reproduced.

**Comment by bartlomiejduda** [comment] 2022-01-05 12:51
@oleavr I have tested this once again after restarting my PC, restarting my phone and re-enabling USB debugging and it seems that there is no need for opening the new issue, because now everything works fine.
I'm using "frida-server-15.1.14-android-arm64" and I have Android 11.

Sorry for the trouble :)

**Comment by qdk0901** [comment] 2022-01-12 04:12
frida-server 15.1.14 and frida-trace 15.1.14 still has problem when inject backboard on iOS 14.7

I open a new issue #1983
