### ISSUE TITLE
Failed to attach: attach_to_process PTRACE_GETREGS failed: 3

### ISSUE THREAD

**Issue by averrin** [frida/frida#23] opened 2015-03-17 16:28 UTC
Error on commands from example:

% frida-trace -i 'recv*' -i 'read*' skype
Failed to attach: attach_to_process PTRACE_GETREGS failed: 3 
% pgrep skype
2084

% cat /etc/issue
Ubuntu 14.04.2 LTS \n \l
% uname -a
Linux 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oleavr** [comment] 2015-03-17 16:32
Did you try changing the `kernel.yama.ptrace_scope` descibed [here](http://www.frida.re/docs/troubleshooting/)? Thinking about adding an explicit check for this in the next release.

**Comment by averrin** [comment] 2015-03-17 16:43
% frida-trace -i 'recv*' skype
Attaching...                                                                
**
ERROR:../../../../frida-core/src/linux/linjector-glue.c:958:frida_resolve_remote_library_function: assertion failed (local_library_path == remote_library_path): ("/lib/x86_64-linux-gnu/libc-2.19.so" == "/lib/i386-linux-gnu/libc-2.19.so")
[1]    12166 abort (core dumped)  frida-trace -i 'recv*' skype

with other programs:
% frida-trace -i 'recv*' dolphin
Started tracing 0 functions. Press ENTER to stop.  
and.... nothing changes.

Looks better=)

**Comment by oleavr** [comment] 2015-03-17 16:51
Ah yes. The first issue is because the latest release doesn't support 32-bit, only 64-bit. I added 32-bit support just a few days ago, and also cross-injection (64->32 and 32->64), so it would be awesome if you could try the latest code in git to verify that it works for you.

The second problem is an embarrassing regression in the latest release. I still have some other bugs left to fix before I'll get to that one, so if you could check if it works better with latest git, that would be really nice!

Thanks for your patience! :)

**Comment by oleavr** [comment] 2015-03-20 01:37
Both issues should now be fixed in the just-released `3.0.1`. I'll announce the release soon, so please let me know if you find any further issues.

**Closed by oleavr** 2015-03-20 01:37 UTC
