### ISSUE TITLE
Spawning app times out on iOS 10.3.2 with Frida 10.6.33

### ISSUE THREAD

**Issue by veehaitch** [frida/frida#415] opened 2018-01-18 10:02 UTC
Invoking e.g., `frida-trace` with `-f` raises a timeout error:

```
SpFailed to spawn: unexpectedly timed out while waiting for app to launch
```

The app is spawned successfully but resumes immediately (`--no-pause` is not given as an argument). This happens independently of the app. Attaching to an already running app works without any issues.

I am on a jailbroken iPhone SE with iOS 10.3.2 using Frida 10.6.33.

**Comment by Daemonceltics** [comment] 2018-01-18 13:27
Spawn do not support iOS .

**Comment by oleavr** [comment] 2018-01-18 13:30
Thanks for reporting. This is most likely a compatibility issue with the jailbreak being used.

@Daemonceltics Spawn is supported. If it doesn't work it's a bug that should be reported.

**Comment by vhaupert** [comment] 2018-01-18 18:00
Thanks for the fast reply! Is there any additional information that I can provide? The jailbreak I use is [g0blin](https://g0blin.sticktron.net/) and it seems to work fine.

**Comment by oleavr** [comment] 2018-01-18 21:43
@veehaitch My guess would be that [our hook](https://github.com/frida/frida-core/blob/0af215e87f10d58c956a8aae081a42dfb7760f8a/src/darwin/agent/launchd.js#L42) isn't hit due to how the jailbreak is set up. Would you be interested in digging into this? I'm afraid I don't have any 10.3 device to reproduce this on, so we'll need your help to get this fixed.

**Comment by Daemonceltics** [comment] 2018-01-19 09:20
@oleavr @veehaitch sorry, maybe old version does't support?My issue #412 Failed to attach: failed to fork (Connection refused), I still not  resolved, any idea?

**Comment by oleavr** [comment] 2018-01-23 14:47
@Daemonceltics Your issue is on Android, this is on iOS.

I'll close this issue as I won't be able to reproduce it, and I will need someone to volunteer their time to debug it on such a device.

**Closed by oleavr** 2018-01-23 14:47 UTC

**Comment by csftech** [comment] 2018-01-27 05:41
@veehaitch Perhaps, it is related to this issue https://github.com/frida/frida-core/pull/165.

Could you help me to figure this out?

First, inject the following script to your launchd. (`frida -U -l launchd.js -p 1 --no-pause`)
[launchd.js](https://gist.github.com/csftech/a0915ff0a32b1c51441584eff19b8345)

Then, click your target app icon on iPhone. you will get `rawIdentifier` output on your terminal.

Final, paste frida output here(you could hide your target app's bundle id before pasting.)
