### ISSUE TITLE
iOS: javascript exceptions while reading memory

### ISSUE THREAD

**Issue by progopis** [frida/frida#55] opened 2015-06-29 14:19 UTC
Hi!

After update to last versions my scripts don't work anymore.
For example, while I doing the following
frida-trace -U -f net.whatsapp.WhatsApp -i "CCCryptorUpdate"
I get the following output (target is crashed and no JS exception thrown)
```
   463 ms	==>CCCryptorRef cryptorRef = 0x160047000
   464 ms	==>const void *dataIn = 0x170251e50
   464 ms	==>size_t dataInLength = 0x20
   464 ms	==>void *dataOut = 0x170251cd0
   464 ms	==>size_t dataOutAvailable = 0x170251e50
   464 ms	==>size_t *dataOutMoved = 0x20
   464 ms	this.size = <0x20>
   464 ms	in_size = <0x20>
   464 ms	===========
   464 ms	CCCryptorUpdate(0x160047000, 0x170251e50, 0x20, 0x170251cd0, 1881480784, &size = 0x20)
   465 ms	---
   466 ms	--return--0x20--
   466 ms	return value 0x0
   466 ms	===========
   474 ms	==>CCCryptorRef cryptorRef = 0x15f848000
   474 ms	==>const void *dataIn = 0x17026c910
   475 ms	==>size_t dataInLength = 0x30
   475 ms	==>void *dataOut = 0x17407e780
   475 ms	==>size_t dataOutAvailable = 0x17026c900
   475 ms	==>size_t *dataOutMoved = 0x18a83da22
Target process terminated.
Stopping...
```
When I trying to attach to the process (with frida-trace -U -i "CCCryptorUpdate" WhatsApp), I get another problem (JS excpetion thrown and processed well):
```
 18816 ms	==>CCCryptorRef cryptorRef = 0x158094a00
 18817 ms	==>const void *dataIn = 0x170669a80
 18817 ms	==>size_t dataInLength = 0x24
 18817 ms	==>void *dataOut = 0x170657e50
 18817 ms	==>size_t dataOutAvailable = 0x30
 18817 ms	==>size_t *dataOutMoved = 0x0
 18817 ms	===========
 18817 ms	CCCryptorUpdate(0x158094a00, 0x170669a80, 0x24, 0x170657e50, 48, &size = 0x0)
 18818 ms	trying to read memory 0x170669a80 with size 0x24
 18822 ms	exception!
 18822 ms	---
 18822 ms	--return--0x0--
 18823 ms	return value 0x0
 18823 ms	===========
 19133 ms	==>CCCryptorRef cryptorRef = 0x15883d200
 19133 ms	==>const void *dataIn = 0x1704513e0
 19133 ms	==>size_t dataInLength = 0x1d
 19133 ms	==>void *dataOut = 0x170642130
 19133 ms	==>size_t dataOutAvailable = 0x0
 19134 ms	==>size_t *dataOutMoved = 0x0
 19135 ms	===========
 19135 ms	CCCryptorUpdate(0x15883d200, 0x1704513e0, 0x1d, 0x170642130, 0, &size = 0x0)
 19135 ms	---
 19136 ms	--return--0x0--
 19136 ms	return value 0x0
 19136 ms	===========
^CStopping...
```
And here my realization:
```javascript
    onEnter: function onEnter(log, args, state) {
		var names = [ "CCCryptorRef cryptorRef", "const void *dataIn", "size_t dataInLength", "void *dataOut", "size_t dataOutAvailable", "size_t *dataOutMoved"];
		for (var i = 0; i < 6; ++i) {
			log("==>" + names[i] + " = " + args[i]);
		}
		this.data_in = args[1];
		var in_size = args[2];
 		this.data_out = args[3];
		var dataOutAvailable = args[4];
		if (dataOutAvailable)
			dataOutAvailable = dataOutAvailable.toInt32();
		this.size = args[5];
		var real_size = this.size;
		if (this.size.toInt32()) {
			log("this.size = <" + this.size + ">");
			log("in_size = <" + in_size + ">");
			//real_size = Memory.readS32(this.size);
		}
		log("===========");
		log("CCCryptorUpdate(" + args[0] + ", " + this.data_in + ", " + in_size + ", " +
				this.data_out + ", " + dataOutAvailable + ", &size = " + real_size + ")");
		if (this.data_in && in_size > 0x20 ) {
			try {
				log("trying to read memory " + this.data_in + " with size " + in_size);
				var bytes = Memory.readByteArray(this.data_in, in_size);
				log("memory was readed");
				var hex_str = "";
				for (var i = 0; i < bytes.length; ++i) {
					hex_str += "0x" + ("0" + bytes[i].toString(16)).slice(-2) + " ";
				}
				log("in data: " + hex_str);
			} catch (e) {
				log("exception!");
			}
		}
		log("---");
	},
...
```
My goal is a universal script for research of mobile cryptography. I have one more question to check the file descriptor for the socket type, but I need to finish the current problem. Btw, my script worked fine with versions before frida 4.2/4.2.5.

**Comment by oleavr** [comment] 2015-06-29 15:49
Hmm, interesting. I do see one issue though:

```JavaScript
var in_size = args[2];
```

but you want:

```JavaScript
var in_size = args[2].toInt32();
```

As you don't want to be comparing the `NativePointer` in `args[2]` to a JavaScript `Number`. Also, the second argument of `Memory.readByteArray()` should be a `Number` and not a `NativePointer`.

Does it work if you change this?

**Comment by progopis** [comment] 2015-06-30 12:06
Thank you, oleavr! This is a great explanation of my mistake! But anyway there is a problem with exception handling while I use "-f" parameter (in the second example exception of incorrect function usage caught). What's the difference between the modes?

**Comment by oleavr** [comment] 2015-06-30 12:13
By the way, make sure you grab the new 4.2.6 release, as it has a bug-fix that you need: it fixes access to args[4] through args[7] on arm64. In 4.2.5 and before we were looking on the stack for those arguments, instead of in the registers (d'oh!).

Good point regarding "-f" btw; the issue is that we install a signal handler very early, even before the application has installed its handler(s), so the application comes after us and replaces our handler. That's why we don't get a JS exception on bad memory access. We could hook the signal handler APIs I suppose, and only chain to the application's handlers for failures that we didn't cause (and revert properly when detaching from the process). It's related to solving frida/frida-gum#6 btw.

**Comment by oleavr** [comment] 2015-12-23 18:05
All mentioned issues are fixed in the latest release.

**Closed by oleavr** 2015-12-23 18:05 UTC
