### ISSUE TITLE
(iPhone XR 13.3, Jailbroken) Cannot use frida-trace

### ISSUE THREAD

**Issue by Squidkingdom** [frida/frida#1192] opened 2020-02-24 04:06 UTC
I'm trying to use Frida to trace methods called that crash a 3rd party app upon opening.

When i run something such as `frida-trace -U -F` or `frida-trace -U -p 2481` it fails and send this error message.```Failed to attach: unexpected error while starting thread (act_set_state returned '(os/kern) protection failure')```

Is this a known issue or am I doing something wrong?

**Comment by Squidkingdom** [comment] 2020-02-24 04:08
I have tried running this as both root and user, and once I got an unable to open `libsystem.b.dylib` citing file or directory doesnt exit. I verified its location and its there (obviously)

**Comment by oleavr** [comment] 2020-02-24 19:57
Duplicate of #885.

**Closed by oleavr** 2020-02-24 19:57 UTC
