### ISSUE TITLE
Add -fPIC to release libfrida-gum.a compilation

### ISSUE THREAD

**Issue by Meteorite** [frida/frida#661] opened 2018-10-06 18:39 UTC
Starting with Frida 12 all released archives `frida-gum-devkit-12.x.x-android-arm.tar.xz` contain `libfrida-gum.a` file, that is compiled without -fPIC flag. That's why `frida-gum-example.c`, that are also included into archive, can't be linked with `libfrida-gum.a`:
```
ld: error: libfrida-gum.a(gthread.c.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
...
ld: error: libfrida-gum.a(trees.c.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
```

Earlier (Frida 11 and lower) releases are Ok. Please, fix modern libfrida-gum releases...

**Comment by oleavr** [comment] 2018-10-07 18:45
The problem is not in frida-gum, but in one of GLib's object files, which we build using `Makefile.sdk.mk`. I've double-checked that `-fPIC` actually makes it to the compiler, so this appears to be a a bug in the Android toolchain. The workaround is to add `-Wl,--gc-sections` when linking, which will eliminate the unused symbols and give you smaller binaries. (The problematic symbols are luckily unused.)

I'll close this as there's already multiple issues open about this same problem.

**Closed by oleavr** 2018-10-07 18:45 UTC
