### ISSUE TITLE
unknown key 'kernel.yama.ptrace_scope' On OnePlus 6

### ISSUE THREAD

**Issue by JReverse** [frida/frida#841] opened 2019-04-14 12:40 UTC
unknown key 'kernel.yama.ptrace_scope'
![image](https://user-images.githubusercontent.com/40630518/56092933-4eac7900-5e88-11e9-9366-65ed0ad03637.png)

On Open Beta 15
Magisk v19.08d4c4072(19004) (Canary build)

Please fix!

**Comment by gorelics** [comment] 2019-04-14 17:48
Magisk 19 module MagiskHide ptracing zygote. Use older version or disable MagiskHide

**Comment by gorelics** [comment] 2019-04-14 17:51
Duplicate of #824

**Closed** 2021-06-23 20:30 UTC
