### ISSUE TITLE
App suddenly crashes in hooked function after Android update to 5.1.1

### ISSUE THREAD

**Issue by Samuirai** [frida/frida#155] opened 2016-07-01 14:35 UTC
Hello,

I've used frida without issues on an old Nexus 7 with Android 4.3. After an android update to 5.1.1 it suddenly crashes the app. I have two different injected script examples that crash differently.

This worked perfectly fine before I upgraded to the new android version. It's the same app. It's the same frida-server binary, the same python script.

It seems like it crashed after the script is loaded, and the app tries to execute something that is hooked.

Some info from the device:
```
root@tilapia:/ # /data/local/tmp/frida-server --version
7.2.2
root@tilapia:/ # ps | grep frida
root      2593  2477  34248  28544 ffffffff 414824e4 S /data/local/tmp/frida-server
root      2644  2643  7816   1960  ffffffff 407274e4 S /data/local/tmp/re.frida.server/frida-helper-32
shell@tilapia:/ $ mount | grep ext4
/dev/block/platform/sdhci-tegra.3/by-name/APP /system ext4 ro,seclabel,relatime,user_xattr,acl,barrier=1 0 0
/dev/block/platform/sdhci-tegra.3/by-name/CAC /cache ext4 rw,seclabel,nosuid,nodev,noatime,errors=panic,user_xattr,acl,barrier=1,nomblk_io_submit,data=ordered 0 0
/dev/block/platform/sdhci-tegra.3/by-name/UDA /data ext4 rw,seclabel,nosuid,nodev,noatime,errors=panic,user_xattr,acl,barrier=1,nomblk_io_submit,data=ordered 0 0
```

Some info from the host:
```
$ python -c 'import frida; print frida.__version__'
7.2.6
```

Python script and first example script:
```python
import frida
import sys

package_name = "com.XXXX.xx"

def get_messages_from_js(message, data):
            print(message)
            print (message['payload'])

def instrument_load_url():
        hook_code = """
        setTimeout(function(){
            Dalvik.perform(function () {
                var WebView = Dalvik.use("android.webkit.WebView");
                WebView.loadDataWithBaseURL.overload("java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String").implementation = function (a,b,c,d,e) {
                    send(a.toString());
                    send(b.toString());
                    send(c.toString());
                    send(d.toString());
                    this.loadDataWithBaseURL.overload("java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String").call(this, a,b,c,d,e);
                };
            });
        },0);
        """
        return hook_code

process = frida.get_device_manager().enumerate_devices()[-1].attach(package_name)
script = process.create_script(instrument_load_url())
script.on('message', get_messages_from_js)
script.load()
sys.stdin.read()
```

logcat output:
```
I/WebViewFactory( 4863): Loading com.google.android.webview version 39 (1836172-arm) (code 324901)
I/LibraryLoader( 4863): Time to load native libraries: ۳ ms (timestamps ۱۱۰-۱۱۳)
I/LibraryLoader( 4863): Expected native library version number "",actual native library version number ""
V/WebViewChromiumFactoryProvider( 4863): Binding Chromium to main looper Looper (main, tid 1) {5449f12}
I/LibraryLoader( 4863): Expected native library version number "",actual native library version number ""
I/chromium( 4863): [INFO:library_loader_hooks.cc(104)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController( 4863): Initializing chromium process, singleProcess=true
W/art     ( 4863): Attempt to remove local handle scope entry from IRT, ignoring
W/chromium( 4863): [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
I/chromium( 4863): [INFO:aw_browser_main_parts.cc(65)] Load from apk succesful, fd=66 off=60752 len=4876
I/chromium( 4863): [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:67 off:230172 len:1089587
D/BluetoothManagerService(  502): Message: 20
D/BluetoothManagerService(  502): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@2c649e84:true
D/BluetoothAdapter( 4863): 10184419: getState() :  mService = null. Returning STATE_OFF
W/chromium( 4863): [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
W/art     ( 4863): Attempt to remove local handle scope entry from IRT, ignoring
W/AwContents( 4863): onDetachedFromWindow called when already detached. Ignoring
W/art     ( 4863): Attempt to remove local handle scope entry from IRT, ignoring
W/art     ( 4863): Attempt to remove local handle scope entry from IRT, ignoring
I/WindowState(  502): WIN DEATH: Window{2ea47fbb u0 com.XXXXX.xx/info.guardianproject.securereaderinterface.MainActivity}
I/Zygote  (  128): Process 4863 exited due to signal (11)
I/ActivityManager(  502): Process com.XXXXX.xx (pid 4863) has died
W/ActivityManager(  502): Scheduling restart of crashed service com.XXXXX.xx/info.guardianproject.securereader.SyncService in 1000ms
W/ActivityManager(  502): Scheduling restart of crashed service com.XXXXX.xx/info.guardianproject.cacheword.CacheWordService in 11000ms
W/ActivityManager(  502): Force removing ActivityRecord{213ef89f u0 com.XXXXX.xx/info.guardianproject.securereaderinterface.MainActivity t29}: app died, no saved state
W/InputMethodManagerService(  502): Got RemoteException sending setActive(false) notification to pid 4863 uid 10084
W/OpenGLRenderer( 1092): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
W/OpenGLRenderer( 1092): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

Another script doing a little bit more:
```javascript
        setTimeout(function(){
        Dalvik.perform(function () {
            var Item = Dalvik.use("com.xxx.xxx.Item");
            Item.getUid.implementation = function () {
                s = this.getUid();
                if(s.startsWith('uid:')) {
                    s += "asd";
                }
                send(s);
                return s;
            };
        });
    },0);
```

Which causes a crash with some more information:

```
F/libc    ( 5061): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 5637 (Thread-329)
I/DEBUG   (  119): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  119): Build fingerprint: 'google/nakasig/tilapia:5.1.1/LMY47V/1836172:user/release-keys'
I/DEBUG   (  119): Revision: '0'
I/DEBUG   (  119): ABI: 'arm'
I/DEBUG   (  119): pid: 5061, tid: 5637, name: Thread-329  >>> com.XXXXX.xxx <<<
I/DEBUG   (  119): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
I/DEBUG   (  119):     r0 422c5ee0  r1 4233a780  r2 4233a780  r3 422ea400
I/DEBUG   (  119):     r4 4241aa60  r5 6c06c9b8  r6 00000000  r7 0b8e0000
I/DEBUG   (  119):     r8 74169628  r9 43474700  sl 43474700  fp 6c06c9f0
I/DEBUG   (  119):     ip 00000001  sp 6c06c970  lr 42110a2b  pc 41f71818  cpsr 20000030
I/DEBUG   (  119):
I/DEBUG   (  119): backtrace:
I/DEBUG   (  119):     #00 pc 000e1818  /system/lib/libart.so
I/DEBUG   (  119):     #01 pc 00280a27  /system/lib/libart.so (artQuickGenericJniTrampoline+34)
I/DEBUG   (  119):     #02 pc 006f0809  /data/dalvik-cache/arm/data@app@com.XXXXX.xxx-1@base.apk@classes.dex
W/ActivityManager(  502):   Force finishing activity 1 com.XXXXX.xxx/info.xxx.xxxxx.MainActivity
I/DEBUG   (  119):
I/DEBUG   (  119): Tombstone written to: /data/tombstones/tombstone_06
W/SurfaceFlinger(  115): FB is protected: PERMISSION_DENIED
I/Choreographer( 5061): Skipped 105 frames!  The application may be doing too much work on its main thread.
W/WindowManager(  502): Screenshot failure taking screenshot for (800x1280) to layer 21010
I/BootReceiver(  502): Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
I/OpenGLRenderer(  502): Initialized EGL, version 1.4
I/WindowState(  502): WIN DEATH: Window{626f0e0 u0 com.XXXXX.xxx/info.xxx.xxxxx.MainActivity}
E/libprocessgroup(  502): failed to kill 1 processes for processgroup 5061
I/ActivityManager(  502): Process com.XXXXX.xxx (pid 5061) has died
W/ActivityManager(  502): Scheduling restart of crashed service com.XXXXX.xxx/info.xxx.xxx.SyncService in 1000ms
W/ActivityManager(  502): Scheduling restart of crashed service com.XXXXX.xxx/info.xxx.xxx.CacheWordService in 11000ms
I/Zygote  (  128): Process 5061 exited due to signal (11)
W/OpenGLRenderer( 1092): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
W/OpenGLRenderer( 1092): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

And the created tombstone has more information. Here some excerpts:

```
Build fingerprint: 'google/nakasig/tilapia:5.1.1/LMY47V/1836172:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 5061, tid: 5637, name: Thread-329  >>> com.XXXXX.xx <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
    r0 422c5ee0  r1 4233a780  r2 4233a780  r3 422ea400
    r4 4241aa60  r5 6c06c9b8  r6 00000000  r7 0b8e0000
    r8 74169628  r9 43474700  sl 43474700  fp 6c06c9f0
    ip 00000001  sp 6c06c970  lr 42110a2b  pc 41f71818  cpsr 20000030
    d0  6573616261746144  d1  0000000000000000
    d2  0000000000000000  d3  0000000000000000
    d4  0000000000000000  d5  0000000000000000
    d6  0000000000000000  d7  000002a000000000
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 000000000006ac00  d17 de2ea56e0dae831e
    d18 da8279993e655ef8  d19 5a8279995a827999
    d20 5a8279995a827999  d21 5a8279995a827999
    d22 17aa657be5f6340b  d23 dee8df0d8970ad16
    d24 e604d51b04042c55  d25 bc45ba546b11f3e5
    d26 62761645da73732a  d27 bb79ab2876aa916b
    d28 5a8279995a827999  d29 5a8279995a827999
    d30 0000000000000000  d31 0000000000000000
    scr 68000013

backtrace:
    #00 pc 000e1818  /system/lib/libart.so
    #01 pc 00280a27  /system/lib/libart.so (artQuickGenericJniTrampoline+34)
    #02 pc 006f0809  /data/dalvik-cache/arm/data@app@com.XXXXX.xx-1@base.apk@classes.dex

stack:
         6c06c930  00000000
         6c06c934  70233018  /data/dalvik-cache/arm/system@framework@boot.art
         6c06c938  7416f648  /dev/ashmem/dalvik-non moving space (deleted)
         6c06c93c  424570e0  /dev/ashmem/dalvik-main space (deleted)
         6c06c940  00000001
         6c06c944  424570e0  /dev/ashmem/dalvik-main space (deleted)
         6c06c948  424191e0  /dev/ashmem/dalvik-main space (deleted)
         6c06c94c  424570e0  /dev/ashmem/dalvik-main space (deleted)
         6c06c950  70233498  /data/dalvik-cache/arm/system@framework@boot.art
         6c06c954  00000001
         6c06c958  00000000
         6c06c95c  7270e89b  /data/dalvik-cache/arm/system@framework@boot.oat
         6c06c960  70233498  /data/dalvik-cache/arm/system@framework@boot.art
         6c06c964  43474280  /dev/ashmem/dalvik-main space (deleted)
         6c06c968  00000001
         6c06c96c  424570e0  /dev/ashmem/dalvik-main space (deleted)
    #00  6c06c970  6c06c9d8
         6c06c974  00000000
         6c06c978  00000000
         6c06c97c  74172b08  /dev/ashmem/dalvik-non moving space (deleted)
         6c06c980  ffffffff
         6c06c984  42110a2b  /system/lib/libart.so (artQuickGenericJniTrampoline+38)
    #01  6c06c988  00000000
         6c06c98c  6c06c9e8
         6c06c990  00000002
         6c06c994  7089afc0  /data/dalvik-cache/arm/system@framework@boot.art
         6c06c998  4217fa58  /system/lib/libart.so
         6c06c99c  43474700  /dev/ashmem/dalvik-main space (deleted)
         6c06c9a0  422ea400  /dev/ashmem/dalvik-main space (deleted)
         6c06c9a4  6c06c9d8
         6c06c9a8  00000020
         6c06c9ac  00000000
         6c06c9b0  00000014
         6c06c9b4  4009aa50
         6c06c9b8  00000000
         6c06c9bc  42109f97  /system/lib/libart.so
         6c06c9c0  6c06c9f0
         6c06c9c4  77ffc2f8
         ........  ........
    #02  6c06ca80  74169628  /dev/ashmem/dalvik-non moving space (deleted)
         6c06ca84  42470220  /dev/ashmem/dalvik-main space (deleted)
         6c06ca88  433a1f40  /dev/ashmem/dalvik-main space (deleted)
         6c06ca8c  00000001
         6c06ca90  7416b948  /dev/ashmem/dalvik-non moving space (deleted)
         6c06ca94  00000001
         6c06ca98  4246a4c0  /dev/ashmem/dalvik-main space (deleted)
         6c06ca9c  427259c0  /dev/ashmem/dalvik-main space (deleted)
         6c06caa0  7416b948  /dev/ashmem/dalvik-non moving space (deleted)
         6c06caa4  70132770  /data/dalvik-cache/arm/system@framework@boot.art
         6c06caa8  00000020
         6c06caac  4359cf60  /dev/ashmem/dalvik-main space (deleted)
         6c06cab0  00000000
         6c06cab4  ffffffff
         6c06cab8  ffffffff
         6c06cabc  00000001
```

Sorry I cannot provide more insight.

kind regards!

**Comment by oleavr** [comment] 2016-08-06 01:20
Thanks for reporting! This is a duplicate of frida/frida-gum#106. (Our ART support is still a work in progress.)

**Closed by oleavr** 2016-08-06 01:20 UTC
