### ISSUE TITLE
Frida Android 11.0.3 method hooking problems.

### ISSUE THREAD

**Issue by clviper** [frida/frida#503] opened 2018-05-16 14:04 UTC
Hi @oleavr .

At least in this two last versions with the same code I was using on version 10.6.39, for my particular scenario I'm having the following errors: 

`Error: can't decode byte 0xc0 in position 726
    at frida/node_modules/frida-java/lib/env.js:922
    at frida/node_modules/frida-java/lib/class-factory.js:2347
    at input:1
    at r (frida/node_modules/frida-java/lib/class-factory.js:1377)
    at [anon] (repl1.js:77)
    at input:1
`

I'm essentially hooking a function that receives a plaintext and encrypts it using AES.
```Java
var Cipher = Java.use("javax.crypto.Cipher");
var StringClass = Java.use("java.lang.String");
var EncryptionClass = Java.use("package.class");
EncryptionClass.ॱ.overload("[B","[B").implementation = function(x,y){
  console.log("Encrypting with AES/CBC with IV");
  var original_value = StringClass.$new(y);
  console.log("Original Value to Encrypt: "+original_value);
  var value = this.ॱ(x,original_value.getBytes());
  return value;
}

Do you have any idea what might have changed in frida code that is creating this problem? This error is triggered on the output of the original_value variable.

The JSON.stringify of that variable is {"$handle":"0x200576","$weakRef":65}, so it seems that what was returned in StringClass.$new() has changed.

Thank you in advance.

Cheers.

**Comment by clviper** [comment] 2018-05-25 09:59
Hi again. Just created a simple POC to help debug this.

With frida 10.6.29 I can output the string without any problems. With frida 11.0.3 I get the error:

`Error: abort was called
    at input:1
    at [anon] (repl1.js:14)
    at input:1
Process terminated
`

It is not the same error, but it might be related.

This is the frida script I'm using

```Javascript
Java.perform(function x() {
	    console.log("");
	    console.log("[.] Testing ByteArray output");
	    var EncryptionClass = Java.use("pt.integrity.labs.aes.MainActivity");
	    var StringClass = Java.use("java.lang.String");
	    EncryptionClass.encrypt.overload("[B").implementation = function(x){
		this.encrypt(x);
		value = StringClass.$new(x);
		console.log("Value to encrypt: "+value);
	    }

});
```

[app-debug.apk.zip](https://github.com/frida/frida/files/2038899/app-debug.apk.zip)

**Comment by oleavr** [comment] 2018-06-06 01:52
Hey @clviper,

Sorry it took a while to have a closer look at this – I'm spread a bit thin.

Really appreciate that excellent test-case! This is indeed a regression. The problem is that `getObjectType()`'s [isCompatible()](https://github.com/frida/frida-java/blob/ab83462218ad689f0b0656314c2ddefeecee5cc2/lib/class-factory.js#L2362-L2370) doesn't actually fully validate whether a JS value is compatible with the given Java type. It just checks if the JS value looks like it's wrapping a Java object, no matter the type, and assumes it is compatible if so. (Ironically there's a TODO about it in the code that's been there since that code was written.)

So the reason this broke is that array values are now wrapped, so they can be passed from JS to Java by reference, which is important if Java code needs to modify an array, e.g. for in-place encryption, and the JS code needs to be able to inspect the mutated array afterwards. So when I made the changes to fix that issue I forgot that we had a really sloppy compatibility check in `getObjectType()`. This means when you do `StringClass.$new(x)` it's going to loop through the different overloads looking for one compatible with `x`. Since the first overload is the one accepting a `java.lang.String` and `x` now looks like a Java object, our `getObjectType()` for `java.lang.String`'s `isCompatible` is going to respond `true`, resulting in an incompatible overload being called. This subsequently terminates the application:
```
E zygote64: JNI ERROR (app bug): attempt to pass an instance of byte[] as argument 1 to java.lang.String java.lang.StringFactory.newStringFromString(java.lang.String)
```

I'll take a stab at fixing that `TODO` now, which should fix this issue and also avoid terminating the application if the Frida user tries to call a Java method with an incompatible object value.

**Comment by oleavr** [comment] 2018-06-06 02:59
Fixed in https://github.com/frida/frida-java/commit/85ef3910a5d177deb7daa197b13d18181f9a6b9d -- releasing 11.0.11 right now with this fix. Thanks a lot for helping track this one down! 🍻🙌

**Closed by oleavr** 2018-06-06 02:59 UTC
