### ISSUE TITLE
Frida gadget not loading on Android.

### ISSUE THREAD

**Issue by glennguy** [frida/frida#426] opened 2018-02-03 12:22 UTC
Hi,

I'm using a HTC One M8 with Lineage OS 14.1 (Nougat 7.1) and have tried injecting into 3 different apps now using Objection. Logcat is showing no Frida related messages at all. The apps are all sitting there at the welcome/splash screens waiting, frida-ps -U is coming back with ```Error: unable to connect to remote frida-server: closed``` 

I've been at it for a couple of hours now, tried a fresh install of Ubuntu 17.10 and reflashed my device with the current firmware (was running CM Android 6.0) and still no luck. Am I doing something wrong, should I try another device or would that not be an issue? Thanks for your help.

**Comment by burrowingsec** [comment] 2018-02-13 09:37
@glennguy I was having the same issue. It seems the latest few versions of the Gadget are broken in some way. I've not had a chance to do a diff between a working version and the newest versions but there's obviously something wrong.

I know this is 10 days after your initial issue but if you still have a need to patch your binary then I suggest manually patching using Frida Gadget 10.6.32. Instructions on how to do that are here: https://koz.io/using-frida-on-android-without-root/

**Comment by glennguy** [comment] 2018-02-13 11:51
Thanks @burrowingsec 
I tried manually as well but with no luck. Still couldn't connect :(

Next step is to try downgrading to Marshmallow. Seems to be a lot more widely supported for these kind of tools.

**Comment by leonjza** [comment] 2018-02-13 11:53
It seems like 10.6.33 is the last version that is working as expected in embedded mode. Any version after that does not show the "I Frida   : Listening on 127.0.0.1 TCP port 27042" message on startup once injected with a `loadLibrary` call.

**Comment by cutler-scott-ey** [comment] 2018-02-15 21:30
I can chime in that, using the instructions mentioned in koz.io, trying to install frida-gadget into an app on a Pixel XL with Android 8.1 causes the app to crash on startup. I tried several version of frida-gadget including 10.6.53, 10.6.33, and 10.6.24. I'm a bit new to Android debugging but if someone needs more detailed information and is willing to find a link with some instructions on getting the necessary info, I can give it a shot.

**Comment by FrankSpierings** [comment] 2018-02-25 11:52
I have been out of the Frida game for a couple of months. Last week I started to play with Frida again and I have also noticed problems when embedding the Frida gadget. I've reverted to using version `10.6.11`, since that one worked correctly a couple months back. I could get `10.6.31` to start, but previously written hooks crashed the Android application.

**Comment by nadirwh** [comment] 2018-02-26 16:07
I can confirm that this works with 10.6.33. Any later versions don't.

**Comment by burrowingsec** [comment] 2018-02-26 16:23
@nadirwh Yep, have done that a few times now. I think when I posted originally @leonjza was still rolling out the update. Super handy stuff.

**Comment by oleavr** [comment] 2018-02-27 02:13
Fixed in Frida 10.6.55.

**Closed by oleavr** 2018-02-27 02:13 UTC
