### ISSUE TITLE
Error: Process not found

### ISSUE THREAD

**Issue by aharris88** [frida/frida#146] opened 2016-05-12 01:09 UTC
I got [this example](https://github.com/aharris88/learn-frida/tree/master/js-hello) (from [this video](https://www.youtube.com/watch?v=4Ag-2LZQM8g)) to work once. The first time it opened up a permissions dialog and I had to type in my password and it worked.

But after the first time, I just get this error:

WARN [Error: Process not found]

What could be wrong? I'm on Mac OS X El Capitan.

**Comment by oleavr** [comment] 2017-01-19 00:36
Should be fixed in latest Frida 9.x – was caused by a stability issue. Sorry for the delay!

**Closed by oleavr** 2017-01-19 00:36 UTC
