### ISSUE TITLE
Target App crashes using frida-trace on Android

### ISSUE THREAD

**Issue by alkman** [frida/frida#218] opened 2017-01-27 18:24 UTC
When I launch the server as root on Android:
angler:/data/local/tmp # ./frida-server-9.0.13-android-arm64                                                                                    
libsepol.avtab_read_item: more than one specifier
libsepol.avtab_read: failed on entry 4 of 11154
Unable to load SELinux policy from the kernel: unsupported policy database format

From my MBP, I can successfully run frida-ps -U to get a list of apps. I get the following with frida-trace:

frida-trace -U -n targetapp -i sendGetRequest
Failed to attach: unexpectedly timed out while waiting for FIFO to establish

On the MBP:
frida --version
9.0.13

Phone is a Nexus 6P
Android 7.1.1 Build NMF26F

**Comment by oleavr** [comment] 2017-02-10 11:14
Duplicate of frida/frida-core#99.

**Closed by oleavr** 2017-02-10 11:14 UTC
